<?php

/**
 * @file
 * Module used to insert the config and drupal files to S3 bucket when a site is added.
 *
 */


/**
 * Loads AWS PHP SDK library
 * 
 * @return array
 */
function _daas_load_awssdk2_library() {
  $library = libraries_load('awssdk2');
  
  return $library;
}

/**
 * Implements hook_libraries_info()
 */
function daas_amazonS3_insert_libraries_info() {
  return array(
    'awssdk2' => array(
      'title' => 'AWS SDK for PHP',
      'vendor url' => 'http://docs.aws.amazon.com/aws-sdk-php/guide/latest/index.html',
      'download url' => 'https://github.com/aws/aws-sdk-php/releases',
      'version' => '2006-03-01',
      
      'files' => array(
        'php' => array(
          'aws-autoloader.php'
        )
      )
    )
  );
}

/**
 * Implements hook_menu().
 */
function daas_amazonS3_insert_menu() {
  $items['admin/config/services/awsconfig'] = array(
    'title' => 'Amazon AWS Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'aws_credentials_config_form'
    ),
    'access arguments' => array(
      'administer users'
    ),
    'type' => MENU_NORMAL_ITEM,
    
    'file' => 'daas_amazonS3_insert.admin.inc'
  );
  
  return $items;
}