<?php
/**
 * @file
 * Allow Hostmaster to configure database servers.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_db_cloud_hosting_service() {
  return array(
    'mysql_cloud' => 'db',
  );
}

/**
 * Find the database server.
 */
function hosting_get_db_cloud($hostname) {
  return hosting_get_db_server($hostname);
}

/**
 * Implements hook_nodeapi_TYPE_OP().
 */
function hosting_db_cloud_nodeapi_server_presave(&$node) {
  if (empty($node->db_passwd) && !empty($node->nid)) {
    $old = node_load($node->nid);

    if (isset($old->db_passwd)) {
      $node->db_passwd = $old->db_passwd;
    }
  }
}

/**
 * Implements hook_views_api().
 */
function hosting_db_cloud_views_api() {
  return module_invoke('hosting_db_server','views_api');
}
